services:
  frontend:
    build:
      context: .
      dockerfile: DockerFile
      args:
        BASE_HREF: /sigaplem/

    container_name: sidocumentacion-frontend

    ports:
      - "8086:80"

    restart: always

    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: DockerFile

    container_name: sidocumentacion-backend

    ports:
      - "3031:3050"

    env_file:
      - ./backend/.env

    environment:
      NODE_ENV: production
      PORT: 3050

    volumes:
      - ./backend/storage:/app/storage

    restart: always
