# ============================================
# Etapa 1: compilar NestJS
# ============================================
FROM node:24-alpine AS build

WORKDIR /app

# IMPORTANTE: durante el build necesitamos devDependencies
ENV NODE_ENV=development

COPY package.json package-lock.json ./

RUN npm ci --include=dev

# Comprobación: debe existir el CLI de Nest
RUN ls -la node_modules/.bin/nest \
    && node_modules/.bin/nest --version

COPY . .

RUN npm run build


# ============================================
# Etapa 2: producción
# ============================================
FROM node:24-alpine AS production

WORKDIR /app

ENV NODE_ENV=production

COPY package.json package-lock.json ./

RUN npm ci --omit=dev \
    && npm cache clean --force

COPY --from=build /app/dist ./dist

RUN mkdir -p /app/storage

EXPOSE 3050

CMD ["node", "dist/main.js"]