# ============================================
# Etapa 1: instalar y compilar NestJS
# ============================================
FROM node:24-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

RUN npm run build


# ============================================
# Etapa 2: imagen final de producción
# ============================================
FROM node:24-alpine AS production

WORKDIR /app

ENV NODE_ENV=production

COPY package.json package-lock.json ./

RUN npm ci --omit=dev \
    && npm cache clean --force

COPY --from=build /app/dist ./dist

# Crea la carpeta persistente de documentos
RUN mkdir -p /app/storage

EXPOSE 3050

CMD ["node", "dist/main.js"]
